packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@better-auth/cli': 1.4.15
  '@better-auth/expo': 1.4.15
  '@eslint/js': ^9.38.0
  '@tailwindcss/postcss': ^4.1.16
  '@tailwindcss/vite': ^4.1.16
  '@tanstack/react-form': ^1.23.8
  '@tanstack/react-query': ^5.90.19
  '@trpc/client': ^11.7.1
  '@trpc/server': ^11.7.1
  '@trpc/tanstack-react-query': ^11.7.1
  '@types/node': 25.0.9
  '@vitejs/plugin-react': 5.1.2
  better-auth: 1.4.15
  eslint: ^9.38.0
  prettier: ^3.8.0
  tailwindcss: ^4.1.16
  typescript: ^5.9.3
  vite: 7.3.1
  zod: ^4.3.5

catalogs:
  react19:
    '@types/react': ~19.2.8
    '@types/react-dom': ~19.2.3
    react: 19.2.3
    react-dom: 19.2.3

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild

overrides:
  '@types/minimatch': 5.1.2
  lightningcss: 1.30.1
  vite: 7.3.1

publicHoistPattern:
  - '@ianvs/prettier-plugin-sort-imports'
  - prettier-plugin-tailwindcss
