packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@better-auth/cli': 1.4.18
  '@better-auth/expo': 1.4.18
  '@eslint/js': ^10.0.1
  '@tailwindcss/postcss': ^4.1.16
  '@tailwindcss/vite': ^4.1.16
  '@tanstack/react-form': ^1.28.3
  '@tanstack/react-query': ^5.90.21
  '@trpc/client': ^11.10.0
  '@trpc/server': ^11.10.0
  '@trpc/tanstack-react-query': ^11.10.0
  '@types/node': 25.2.3
  '@vitejs/plugin-react': 5.1.4
  better-auth: 1.4.18
  eslint: ^10.0.0
  prettier: ^3.8.1
  tailwindcss: ^4.1.16
  typescript: ^5.9.3
  vite: 7.3.1
  zod: ^4.3.6

catalogs:
  react19:
    '@types/react': ~19.2.14
    '@types/react-dom': ~19.2.3
    react: 19.2.4
    react-dom: 19.2.4

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild

overrides:
  '@types/minimatch': 5.1.2
  lightningcss: 1.30.1
  vite: 7.3.1

publicHoistPattern:
  - '@ianvs/prettier-plugin-sort-imports'
  - prettier-plugin-tailwindcss
